version: '3'

services:

########################
# Setup node container
########################
  server:
    build:
      context: ./backend
    expose:
        - "9000"
    ports:
      - 9000:9000
    volumes:
      - ./backend/src:/app/server/src


########################
# Setup client container
########################
  client:
    build: 
      context: ./frontend
    expose:
      - "8000"
    ports:
      - 8000:8000
    volumes:
      - ./frontend/src:/app/client/src
    networks:
      - selenium-grid

########################
# Setup data container
########################
  data:
    build: ./data
    expose:
      - "3001"
    ports:
      - 3001:3001
    volumes:
      - ./data:/app/data
    networks:
      - selenium-grid

########################
# Setup test containers
########################

  hub:
    image: selenium/hub
    ports:
      - "4444"
    networks:
      - selenium-grid

  firefox:
    image: selenium/node-firefox
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    ports:
      - 5900:5900
    depends_on:
      - hub
    networks:
      - selenium-grid

  chrome:
    image: selenium/node-chrome
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    ports:
      - 5901:5900
    depends_on:
      - hub
    networks:
      - selenium-grid

  test-chrome:
    build: robot 
    command: -v BROWSER:gc --outputdir /out /tests
    volumes:
      - ./tests:/app/robot/tests
      - ./results/gc:/app/robot/out
    depends_on: 
      - client
      - chrome
      - data
    networks:
      - selenium-grid

  test-firefox:
    build: robot 
    command: -v BROWSER:ff --outputdir /out /tests
    volumes:
      - ./tests:/app/robot/tests
      - ./results/gc:/app/robot/out
    depends_on: 
      - client
      - firefox
      - data
    networks:
      - selenium-grid

networks:
  selenium-grid: